server:
  port: 8883

zeebe.client:
  broker:
    gateway-address: localhost:26500
  security:
    plaintext: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
